version: '3.8'

services:
  prefect:
    image: prefecthq/prefect:3-python3.12
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0
    network_mode: host
    restart: unless-stopped
