version: '3.8'

services:
  postgres:
    image: postgres:16
    command: ["postgres", "-p", "5432", "-c", "logging_collector=on"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hydra_data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data



  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS="--appendonly yes"
   # volumes:
     # - redis-data:/data

    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9050:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

    command: server /data --console-address ":9001"


volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
  minio-data:
    driver: local