[project]
name = "workflows"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "minio>=7.2.16",
    "prefect>=3.4.11",
    "prisma>=0.15.0",
    "pyodm>=1.5.12",
]
